apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: udagram-instagram
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: mohaerradi/frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80            
      restartPolicy: Always